

version: "3.3"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: changeme
        MYSQL_PASSWORD: changeme
        MYSQL_USERD: kiarash
        MYSQL_DATABASE: tacos
    volumes:
      - ~/mysqldata:/var/lib/mysql
    networks:
      - jnet

  builder:
    image: gradle:jdk12  # same version to be set in Dockerfile 
    hostname: builder
    container_name: builder
    working_dir: /src
    command: >
        bash -c "gradle bootJar
        && cp -r build/libs/* /app/"
    volumes:
        - .:/src
        - /tmp/app:/app
    networks:
      - jnet


  japp:
    image: mytacos
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1    
    hostname: japp
    container_name: japp
    working_dir: /japp
    ports:
      - 8080:8080
    networks:
      - jnet

networks:
    jnet:

volumes:
    builtApp:        